#!/bin/bash
clear

touch SampleFile
for((i=0;i<50000;i++))
do
s=""
for((j=0;j<500;j++))
do
if test $j = 499
then
d=$(date +"%m -%d-%Y")
s=$s" R"$i"c"$d
else
s=$s" R"$i"c"$j
fi
done
echo $s>> "SampleFile"
done


#hadoop fs -mkdir /user/hive/reet1

#hadoop fs -ls /user/hive/reet1

# create static partition table

SET hive.exec.dynamic.partition=false;
SET hive.exec.dynamic.partition.mode=strict;

create External table if not exists TableCars(Name String,make String,model String) partitioned by(Yea
r Date)
stored as textfile;




load data local inpath "/home/cloudera/workspace/SampleFile" overwrite into table TableCars partition 
(Year = '2018-04-22');

#creating hive managed table

 create table hive_table(name string,make string, model string,year date);

load data local inpath "/home/cloudera/workspace/SampleFile" overwrite into table hive_table;
