#!/bin/bash

clear

today="$(date +'%Y -%m -%d')"

for((i = 1; i<=9;i++))
do

		if (($i % 3 == 0))
		then
		today=$(date +"%Y -%m -%d" -d "$(date) +$i day ")
		fi

	s=$today" "Hello1" "Hello2" "Hello3

for((k=1;k<4;k++))
	do
		s=$s" "$k
	done
	
	echo $s>> "DynamicSampleFile"
done
